#cloud-config
hostname: traefik-dev
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - net-tools
  - wget
  - unzip

runcmd:
  - mkdir -p /home/ubuntu/traefik
  - chown -R ubuntu:ubuntu /home/ubuntu/traefik
  - mkdir -p /etc/traefik
  - mkdir -p /var/log/traefik
  - echo "System prepared for Traefik installation"
