version: "3.8"

services:
  nginx-app1:
    image: nginx:alpine
    container_name: nginx-app1
    ports:
      - "8081:80"
    volumes:
      - ./html/app1:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx-app2:
    image: nginx:alpine
    container_name: nginx-app2
    ports:
      - "8082:80"
    volumes:
      - ./html/app2:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx-app3:
    image: nginx:alpine
    container_name: nginx-app3
    ports:
      - "8083:80"
    volumes:
      - ./html/app3:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx-app4:
    image: nginx:alpine
    container_name: nginx-app4
    ports:
      - "8084:80"
    volumes:
      - ./html/app4:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
